"""add profiles and teams

Revision ID: 0ffe96275d83
Revises: bc232e2de0ee
Create Date: 2026-09-10 17:49:01.494175

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ffe96275d83"
down_revision: str | Sequence[str] | None = "bc232e2de0ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=127), nullable=False),
        sa.Column("group", sa.String(length=31), nullable=False),
        sa.Column("telegram", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("profiles_pkey")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_code", sa.String(length=6), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("teams_pkey")),
        sa.UniqueConstraint("public_code", name=op.f("teams_public_code_key")),
    )
    op.create_foreign_key(
        op.f("profiles_team_id_fkey"),
        "profiles",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("teams_leader_id_fkey"),
        "teams",
        "profiles",
        ["leader_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("teams")
    op.drop_table("profiles")
    # ### end Alembic commands ###
