"""initial

Revision ID: 9d4cfe793bdd
Revises:
Create Date: 2026-09-10 18:25:32.823483

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d4cfe793bdd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Integer(), nullable=False, autoincrement=False),
        sa.Column("full_name", sa.String(length=127), nullable=False),
        sa.Column("group", sa.String(length=31), nullable=False),
        sa.Column("telegram", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("profiles_pkey")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_code", sa.String(length=6), nullable=False),
        sa.Column("name", sa.String(length=127), nullable=False),
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("teams_pkey")),
        sa.UniqueConstraint("public_code", name=op.f("teams_public_code_key")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("passhash", sa.String(length=127), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("utm_source", sa.String(length=63), nullable=True),
        sa.Column("utm_campaign", sa.String(length=63), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_foreign_key(
        op.f("profiles_team_id_fkey"), "profiles", "teams", ["team_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("teams_leader_id_fkey"), "teams", "profiles", ["leader_id"], ["user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_constraint("profiles_team_id_fkey", table_name="profiles")
    op.drop_constraint("teams_leader_id_fkey", table_name="teams")
    op.drop_table("teams")
    op.drop_table("profiles")
    # ### end Alembic commands ###
