"""add tasks and ratings tables

Revision ID: e1b66c39b367
Revises: 9d4cfe793bdd
Create Date: 2026-09-20 22:58:56.075687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1b66c39b367"
down_revision: Union[str, Sequence[str], None] = "9d4cfe793bdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("open_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("modules_pkey")),
    )
    op.create_table(
        "sections",
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("sections_module_id_fkey")
        ),
        sa.PrimaryKeyConstraint("module_id", "number", name=op.f("sections_pkey")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("section_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("manual_review", sa.Boolean(), nullable=False),
        sa.Column("require_task_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_id", "section_number"],
            ["sections.module_id", "sections.number"],
            name="tasks_section_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"], ["modules.id"], name=op.f("tasks_module_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["require_task_id"], ["tasks.id"], name=op.f("tasks_require_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_pkey")),
        sa.UniqueConstraint("module_id", "number", name=op.f("tasks_module_id_key")),
    )
    op.create_table(
        "states",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CLOSED",
                "OPENED",
                "STARTED",
                "REVIEW",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                name="task_status",
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("states_task_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("states_team_id_fkey")
        ),
        sa.PrimaryKeyConstraint("team_id", "task_id", name=op.f("states_pkey")),
    )
    op.create_table(
        "task_media",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column(
            "media_type",
            sa.Enum("FILE", "IMAGE", "VIDEO", "AUDIO", name="media_type"),
            nullable=False,
        ),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("task_media_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("task_id", "number", name=op.f("task_media_pkey")),
    )
    op.create_table(
        "task_questions",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum("TEXT", "FILE", name="question_type"),
            nullable=False,
        ),
        sa.Column("regex", sa.String(length=255), nullable=True),
        sa.Column("supported_exts", sa.ARRAY(sa.String(length=15)), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("task_questions_task_id_fkey")
        ),
        sa.PrimaryKeyConstraint("task_id", "number", name=op.f("task_questions_pkey")),
    )
    op.create_table(
        "task_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id", "question_number"],
            ["task_questions.task_id", "task_questions.number"],
            name=op.f("task_answers_task_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_answers_pkey")),
        sa.UniqueConstraint(
            "task_id", "question_number", "text", name=op.f("task_answers_task_id_key")
        ),
    )
    op.create_table(
        "team_answers",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("question_number", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id", "question_number"],
            ["task_questions.task_id", "task_questions.number"],
            name=op.f("team_answers_task_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("team_answers_team_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "team_id", "task_id", "question_number", name=op.f("team_answers_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_answers")
    op.drop_table("task_answers")
    op.drop_table("task_questions")
    op.drop_table("task_media")
    op.drop_table("states")
    op.drop_table("tasks")
    op.drop_table("sections")
    op.drop_table("modules")
    # ### end Alembic commands ###
    # Postgres не удаляет ENUM-типы вместе с таблицами — иначе повторный
    # upgrade после этого downgrade падает с "type already exists".
    sa.Enum(name="task_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="media_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="question_type").drop(op.get_bind(), checkfirst=True)
